[package]
name = "newengine_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
log = "0.4"
env_logger = "0.11"

serde = { version = "1", features = ["derive"] }
toml = "0.8"

winit = "0.30"
ctrlc = "3.4"